jobs:
- name: run-terrraform
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true

  - task: runtf
    config:
      platform: linux
      image_resource:
         type: docker-image
         source: {repository: rnrbarbosa/terraform_alpine}
      inputs:
      - name: test
        path: .
      run:
        path: ./test/run

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/rnrbarbosa/test.git
    branch: master
