jobs:
- name: run-terraform
  plan:
  - get: test
  - task: run-terraform
    file: test/run.yml


resources:
- name: test
  type: git
  source:
    uri: https://github.com/rnrbarbosa/test.git
    branch: master
