jobs:
- name: run-terrraform
  serial: true
  plan:
  - get: repo
  - task: hello-world
    file: repo/run.yml


resources:
- name: repo
  type: git
  source:
    uri: https://github.com/rnrbarbosa/test.git
    branch: master
