jobs:
- name: run-terraform
  plan:
  - get: repo
  - task: run-terraform
    file: repo/run.yml


resources:
- name: repo
  type: git
  source:
    uri: https://github.com/rnrbarbosa/test.git
    branch: master
